{% set version = "23.3" %}

package:
  name: hwinfo
  version: {{ version }}

source:
  url: https://github.com/openSUSE/hwinfo/archive/{{ version }}.tar.gz
  sha256: ee7f1cb15bde7d6d40cc5f70e382dbaa8264a12f0b1692eba23f14ea146c0e0d
  patches:
    - use_flex_instead_of_lex.patch

build:
  skip: true  # [not linux]
  number: 0
  run_exports:
    - {{ pin_subpackage('hwinfo', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - flex
  host:
    - libx86emu
    - libuuid

test:
  commands:
    - hwinfo
    - test -f ${PREFIX}/lib/libhd.so
    - test -f ${PREFIX}/include/hd.h

about:
  home: https://github.com/openSUSE/hwinfo
  summary: hwinfo/libhd are used to probe for the hardware present in the system
  description: |
    hwinfo/libhd are used to probe for the hardware present in the system. It
    can be used to generate a system overview log which can be later used for
    support.

    This project provides a hardware probing library libhd.so and a command
    line tool hwinfo using it. A major project using this library is YaST, the
    SUSE installation tool.

  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - hmaarrfk
